### PR TITLE
Update slack link on README.md

### LINKED ISSUE #340: Outdated Slack link
On https://github.com/firecracker-microvm/firecracker-go-sdk/blob/main/README.md#questions, the Slack link doesn't work: https://tinyurl.com/firecracker-microvm

image

I suppose it should be updated as in https://github.com/firecracker-microvm/firecracker/commit/7b0f0161532692f23d648cdfd1d4cdea2c8fb65b :)

### PR DESCRIPTION
**Pull request by RoyceDavison**
To fix #340: Outdated Slack link

Signed-off-by: Royce Zhao <qiqinzha@amazon.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by kzys — COMMENTED** [review]
While it is better than what we have - the broken link, I have two questions;

- Can we update `tinyurl.com/firecracker-microvm` instead?
- If we cannot, how about using a direct link rather than relying on tinyurl.com? URL Shorteners don't give us much benefits here.

**Comment by RoyceDavison** [comment]
> While it is better than what we have - the broken link, I have two questions;
> 
> * Can we update `tinyurl.com/firecracker-microvm` instead?
> * If we cannot, how about using a direct link rather than relying on tinyurl.com? URL Shorteners don't give us much benefits here.

I tried with the url you just mentioned, unfortunately we can't use it. I replaced the tinyurl with the original url.

**Review by kzys — APPROVED** [review]

**Comment by kzys** [comment]
You can mention the issue in the commit message. Then GitHub automatically closes the issue upon merge.

https://guides.github.com/features/issues/#notifications

**Comment by RoyceDavison** [comment]
> You can mention the issue in the commit message. Then GitHub automatically closes the issue upon merge.
> 
> https://guides.github.com/features/issues/#notifications

Good to know that, will use this trick in the next time.

**Pull request merged**
