### PR TITLE
Add support for the MMDS configuration.

### PR DESCRIPTION
**Pull request by yjuba**
The goal of this PR is to support the configuration of MMDS in the SDK.

*Issue #, if available:*

*Description of changes:*
- Add a handler to call `mmds/config` in handlers.go.
- Add a wrapper to call `mmds/config` in firecracker.go.
- Add a wrapped function call to machine.go.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kzys** [comment]
The handler looks good. How about adding the IP address to Config struct?

**Comment by yjuba** [comment]
Thank you for your comment.
I was wondering if I should add the IP address to the Config struct, so I would like to add it.

**Comment by kzys** [comment]
Sorry for the late reply. Looks good to me. Can you rebase the branch against master? You don't have to change go.mod and go.sum if they conflict. This PR doesn't add any new dependencies.

**Comment by yjuba** [comment]
Thank you for your comment.
Please check it because it has been rebased.

I haven't made any changes to the code, but the test timed out.
Do you have any idea of ​​the cause?

**Comment by kzys** [comment]
That's odd. Let me restart the BuildKite test.

**Comment by kzys** [comment]
The error we have right now is `find: ‘./testdata/TestCNI/cni.cache/results’: Permission denied` which is not related to this PR.

**Review by kzys — APPROVED** [review]

**Pull request merged**
