### PR TITLE
Copy swagger of firecracker v0.24.0 and nits

### PR DESCRIPTION
**Pull request by RoyceDavison**
Firecracker 0.24.0 adds new API calls for memory ballooning. The goal of this PR is to port the memory ballooning relevant calls to the SDK.

*Issue #, if available:*
*Description of changes:*
* Added relevant Balloon, BalloonUpdate, BalloonStats, BalloonStatsUpdate definitions to client/swagger.yaml
* Generated the updated API client
* Update the firecracker_version in Makefile

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kzys** [comment]
Do you know why the tests are failing? Did it work on your development host?

**Comment by RoyceDavison** [comment]
> Do you know why the tests are failing? Did it work on your development host?

I have no idea. But it did pass all the tests on my remote i3.metal instance.

**Comment by IRCody** [comment]
The errors on buildkite seem to be:

* No DCO -- Need to sign your commits.
* Run go mod tidy first -- the go mod tidy result is different than what's committed here.
* All the test failures seem to be from testdata/firecracker not being downloaded. It's looking at https://github.com/firecracker-microvm/firecracker/releases/download/v0.24.1/firecracker-v0.24.1-x86_64 which doesn't exist.

**Comment by IRCody** [comment]
> The errors on buildkite seem to be:
> 
>     * No DCO -- Need to sign your commits.
>     * Run go mod tidy first -- the go mod tidy result is different than what's committed here.

Latest commit fixes these.

>     * All the test failures seem to be from testdata/firecracker not being downloaded. It's looking at https://github.com/firecracker-microvm/firecracker/releases/download/v0.24.1/firecracker-v0.24.1-x86_64 which doesn't exist.

This is because firecracker changed how it packages these binaries up. They are now released in a tgz file together and need to be downloaded and extracted. The makefile will need to be updated to do this (not necessarily as part of this PR).

**Comment by kzys** [comment]
Do you want to merge this pull request before #332?

**Comment by RoyceDavison** [comment]
> Do you want to merge this pull request before #332?

Yeah, I was waiting for the updated swagger definition with amount_Mib get fixed. But we can merge this one, and merge another update later.

**Review by kzys — APPROVED** [review]

**Pull request merged**
